  export const product = [
    {
      id: 1,
      title: 'Ada banyak peralatan olahraga sepak bola yang dapat kamu beli agar permainan kamu lebih baik',
      category: 'Sepak Bola ',
      image:'https://cdn.pixabay.com/photo/2018/06/12/20/17/soccer-3471402_1280.jpg',
    },
    {
      id: 2,
      title: 'Disini petunjuk peralatan olahraga badminton yang wajib kamu beli',
      category: 'Badminton',
      image: 'https://cdn.pixabay.com/photo/2016/05/31/23/21/badminton-1428046_1280.jpg',
    },
    {
      id: 3,
      title: 'Disini terdapat rekomendasi peralatan tenis dari berbagai merek',
      category: 'Tennis',
      image: 'https://cdn.pixabay.com/photo/2021/08/09/14/56/tennis-6533589_1280.jpg',
    },
    {
      id: 4,
      title: 'Ada banyak jenis merek bola, pakaian dan aksesoris basket',
      category: 'Basket',
      image: 'https://cdn.pixabay.com/photo/2016/11/18/22/10/man-1837119_1280.jpg',
    },
    {
      id: 5,
      title: 'Beragam merek bola voli yang bisa menjadi referensi sebelum membeli',
      category: 'Voli',
      image: 'https://cdn.pixabay.com/photo/2021/07/21/20/11/beach-volleyball-6483905_1280.jpg',
    },
    {
      id: 6,
      category: 'Badminton',
      image: 'https://marketplace.canva.com/EAFn2B---Eg/1/0/1131w/canva-merah-dan-hijau-ilustrasi-badminton-rutin-a4-yCRLF3E-Qtw.jpg',
      createdAt: '28 Aug, 2023',
    },
    {
      id: 7,
      category: 'Basket',
      image: 'https://img.freepik.com/free-vector/colored-vintage-basketball-championship-poster_1284-39316.jpg',
      createdAt: '24 Aug, 2023',
    },
    {
      id: 8,
      category: 'Tennis',
      image: 'https://i.pinimg.com/736x/9b/ba/13/9bba1341fe2e63cb44ae8640e81bd642.jpg',
      createdAt: '15 March, 2023',
    },
    {
      id: 9,
      category: 'Voli',
      image: 'https://marketplace.canva.com/EADkSH2NGg8/1/0/1131w/canva-biru-dan-kuning-turnamen-bola-voli-poster-2WLxudAYV04.jpg',
      createdAt: '8 Aug, 2019',
    },
    {
      id: 10,
      category: 'Sepak Bola',
      image: 'https://marketplace.canva.com/EAFrsqv6wps/1/0/1131w/canva-kuning-hijau-simpel-ilustrasi-kompetisi-futsal-poster-7X4ud5Cbxqw.jpg',
      createdAt: '28 Mei, 2023',
    },
    {
      id: 11,
      title: 'Menggunakan frame HM Graphite / Tungsten dan Shaftnya menggunakan	HM Graphite / NANOMESH NEO kemudian untuk length 10 mm longer',
      category: 'Astrox 3 DG ST',
      createdAt: 'Rp450.000.00',
      image: 'https://www.yonex.com/media/catalog/product/a/x/ax3dg-st.png?quality=80&fit=bounds&height=819&width=600&canvas=600:819',
    },
    {
      id: 12,
      title: 'Menggunakan frame	Aluminum dan shaft menggunakan	Graphite lalu untuk weightnya Grip	3U (Avg. 88g)',
      category: 'Astrox E 13',
      image: 'https://www.yonex.com/media/catalog/product/a/x/axe13_blackblue.png?quality=80&fit=bounds&height=819&width=600&canvas=600:819',
      createdAt: 'Rp1.000.000.00',
    },
    {
      id: 13,
      title : 'YONEX AEROSENSA shuttlecocks are the official shuttlecock for the world’s leading international tournaments. ',
      category: 'Aerosensa 50',
      image: 'https://www.yonex.com/media/catalog/product/a/e/aerosensa_50.png?quality=80&fit=bounds&height=819&width=600&canvas=600:819',
      createdAt: 'Rp200.000.00',
    },
    {
      id: 14,
      title : 'The combination of close-to-feather shuttlecock flight performance and four to five times more durability ',
      category: 'Mavis 2000',
      image: 'https://www.yonex.com/media/catalog/product/m/a/mavis2000w.png?quality=80&fit=bounds&height=819&width=600&canvas=600:819',
      createdAt: 'Rp150.000.00',
    },
    {
      id: 15,
      title : 'Terdapat color(s) yaitu	New Color Lightning Yellow launching June 2023, Sky Blue, Black, Black / Orange, dan untuk sizenya (LxWxH)	75 x 13 x 30cm',
      category: 'Team Tournamet Bag',
      image: 'https://www.yonex.com/media/catalog/product/b/a/ba42331w_bkor.png?quality=80&fit=bounds&height=819&width=600&canvas=600:819',
      createdAt: 'Rp400.000.00',
    },
    {
      id: 16,
      category: 'Pro Racquet Bag',
      title : 'Terdapat color(s) yaitu New Color Mist Purpl Smash Pink,Fine Blue, Tango Red, Green Purple, Black, dan untk sizenya (LxWxH)	78 x 38 x 34 cm',
      image: 'https://www.yonex.com/media/catalog/product/b/a/ba92229_tagr.png?quality=80&fit=bounds&height=819&width=600&canvas=600:819',
      createdAt: 'Rp700.000.00',
    },
    {
      id: 17,
      title : 'Terdapat color(s) yaitu New Color Lightning Yellow launching June 2023, Black, Fine Blue dan untuk sizenya (LxWxH)	31 x 20.5 x 47 cm (26L)',
      category: 'Pro Backpack M',
      image: 'https://www.yonex.com/media/catalog/product/b/a/ba92212m_lny.png?quality=80&fit=bounds&height=819&width=600&canvas=600:819',
      createdAt: 'Rp800.000.00',
    },
    
  ];
  
  export const event = [
    {
      id: 1,
      title : 'Diselenggarakan di Gor Pacitan 30 Aug 2023 pukul 19.00 WIB ',
      category: 'Badminton',
      image: 'https://marketplace.canva.com/EAFn2B---Eg/1/0/1131w/canva-merah-dan-hijau-ilustrasi-badminton-rutin-a4-yCRLF3E-Qtw.jpg',
      createdAt: '28 Aug, 2023',
    },
    {
      id: 2,
      category: 'Basket',
      title : 'Diselenggarakan di Lapangan ITN 2 Malang 28 Aug 2023 pukul 15.00 WIB ',
      image: 'https://img.freepik.com/free-vector/colored-vintage-basketball-championship-poster_1284-39316.jpg',
      createdAt: '24 Aug, 2023',
    },
    {
      id: 3,
      category: 'Tennis',
      title : 'Diselenggarakan di Lapangan Singosari 20 March 2023 pukul 16.00 WIB ',
      image: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/tennis-poster-design-template-129fa4d1a11e810f4a1bc0514588334b_screen.jpg?ts=1645879031',
      createdAt: '15 March, 2023',
      totalComments: 89,
    },
    {
      id: 4,
      category: 'Voli',
      title : 'Diselenggarakan di Lapangan SM 10 March 2023 pukul 15.00 WIB ',
      image: 'https://d1csarkz8obe9u.cloudfront.net/posterpreviews/event-flyer%2Cfootball-flyer%2Csoccer-flyer-design-template-5051f2d1316bafc8d97bfff9ec71c0ca_screen.jpg?ts=1637004790',
      createdAt: '8 March, 2023',
    },
    {
      id: 5,
      category: 'Sepak Bola',
      title : 'Diselenggarakan di Lapangan Lowokwaru 30 Mei 2023 pukul 20.00 WIB ',
      image: 'https://marketplace.canva.com/EAFrsqv6wps/1/0/1131w/canva-kuning-hijau-simpel-ilustrasi-kompetisi-futsal-poster-7X4ud5Cbxqw.jpg',
      createdAt: '28 Mei, 2023',
    },
    
  ];
